# Reusable option lists
US_STATES = [
    {"value": "Alabama", "label": "Alabama"},
    {"value": "Alaska", "label": "Alaska"},
    {"value": "Arizona", "label": "Arizona"},
    {"value": "Arkansas", "label": "Arkansas"},
    {"value": "California", "label": "California"},
    {"value": "Colorado", "label": "Colorado"},
    {"value": "Connecticut", "label": "Connecticut"},
    {"value": "Delaware", "label": "Delaware"},
    {"value": "Florida", "label": "Florida"},
    {"value": "Georgia", "label": "Georgia"},
    {"value": "Hawaii", "label": "Hawaii"},
    {"value": "Idaho", "label": "Idaho"},
    {"value": "Illinois", "label": "Illinois"},
    {"value": "Indiana", "label": "Indiana"},
    {"value": "Iowa", "label": "Iowa"},
    {"value": "Kansas", "label": "Kansas"},
    {"value": "Kentucky", "label": "Kentucky"},
    {"value": "Louisiana", "label": "Louisiana"},
    {"value": "Maine", "label": "Maine"},
    {"value": "Maryland", "label": "Maryland"},
    {"value": "Massachusetts", "label": "Massachusetts"},
    {"value": "Michigan", "label": "Michigan"},
    {"value": "Minnesota", "label": "Minnesota"},
    {"value": "Mississippi", "label": "Mississippi"},
    {"value": "Missouri", "label": "Missouri"},
    {"value": "Montana", "label": "Montana"},
    {"value": "Nebraska", "label": "Nebraska"},
    {"value": "Nevada", "label": "Nevada"},
    {"value": "New Hampshire", "label": "New Hampshire"},
    {"value": "New Jersey", "label": "New Jersey"},
    {"value": "New Mexico", "label": "New Mexico"},
    {"value": "New York", "label": "New York"},
    {"value": "North Carolina", "label": "North Carolina"},
    {"value": "North Dakota", "label": "North Dakota"},
    {"value": "Ohio", "label": "Ohio"},
    {"value": "Oklahoma", "label": "Oklahoma"},
    {"value": "Oregon", "label": "Oregon"},
    {"value": "Pennsylvania", "label": "Pennsylvania"},
    {"value": "Rhode Island", "label": "Rhode Island"},
    {"value": "South Carolina", "label": "South Carolina"},
    {"value": "South Dakota", "label": "South Dakota"},
    {"value": "Tennessee", "label": "Tennessee"},
    {"value": "Texas", "label": "Texas"},
    {"value": "Utah", "label": "Utah"},
    {"value": "Vermont", "label": "Vermont"},
    {"value": "Virginia", "label": "Virginia"},
    {"value": "Washington", "label": "Washington"},
    {"value": "West Virginia", "label": "West Virginia"},
    {"value": "Wisconsin", "label": "Wisconsin"},
    {"value": "Wyoming", "label": "Wyoming"},
]

CATEGORIES = {
    "ids": {
        "label": "Family IDs",
        "icon": "id-card",
        "slug": "ids",
        "subcategories": {
            "drivers_license": {
                "label": "Driver's Licenses",
                "icon": "car",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "license_number", "label": "License Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "state", "label": "State", "type": "text", "required": True},
                    {"key": "issue_date", "label": "Issue Date", "type": "date", "required": False},
                    {"key": "expiration_date", "label": "Expiration Date", "type": "date", "required": True},
                ],
                "file_slots": ["front_image", "back_image"],
                "recommended": True,
            },
            "passport": {
                "label": "Passports",
                "icon": "globe",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "passport_number", "label": "Passport Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "country", "label": "Country", "type": "text", "required": True},
                    {"key": "issue_date", "label": "Issue Date", "type": "date", "required": False},
                    {"key": "expiration_date", "label": "Expiration Date", "type": "date", "required": True},
                ],
                "file_slots": ["front_image", "back_image"],
                "recommended": True,
            },
            "visa": {
                "label": "Visas",
                "icon": "plane",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "country", "label": "Issuing Country", "type": "text", "required": True},
                    {"key": "visa_type", "label": "Visa Type", "type": "text", "required": True},
                    {"key": "visa_number", "label": "Visa Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "passport_number", "label": "Passport Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "issue_date", "label": "Issue Date", "type": "date", "required": False},
                    {"key": "expiration_date", "label": "Expiration Date", "type": "date", "required": True},
                    {"key": "entry_type", "label": "Entry Type", "type": "select", "required": False, "options": [
                        {"value": "Single Entry", "label": "Single Entry"},
                        {"value": "Multiple Entry", "label": "Multiple Entry"},
                        {"value": "Double Entry", "label": "Double Entry"},
                        {"value": "Transit", "label": "Transit"},
                    ]},
                ],
                "file_slots": ["front_image", "back_image"],
                "recommended": True,
            },
            "social_security": {
                "label": "Social Security Cards",
                "icon": "shield",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "ssn", "label": "SSN", "type": "text", "required": True, "encrypted": True},
                ],
                "file_slots": ["front_image", "back_image"],
                "recommended": True,
            },
            "birth_certificate": {
                "label": "Birth Certificates",
                "icon": "file-text",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "date_of_birth", "label": "Date of Birth", "type": "date", "required": True},
                    {"key": "place_of_birth", "label": "Place of Birth", "type": "text", "required": False},
                    {"key": "certificate_number", "label": "Certificate Number", "type": "text", "required": False, "encrypted": True},
                ],
                "file_slots": ["document"],
                "recommended": True,
            },
            "custom_id": {
                "label": "Custom IDs",
                "icon": "badge",
                "fields": [
                    {"key": "full_name", "label": "Full Name", "type": "text", "required": True},
                    {"key": "id_type", "label": "ID Type", "type": "text", "required": True},
                    {"key": "id_number", "label": "ID Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "issuing_body", "label": "Issuing Body", "type": "text", "required": False},
                    {"key": "issue_date", "label": "Issue Date", "type": "date", "required": False},
                    {"key": "expiration_date", "label": "Expiration Date", "type": "date", "required": False},
                ],
                "file_slots": ["front_image", "back_image", "document"],
                "recommended": False,
            },
            "personal_tax": {
                "label": "Tax Documents",
                "icon": "file-text",
                "fields": [
                    {"key": "document_type", "label": "Document Type", "type": "text", "required": True},
                    {"key": "tax_year", "label": "Tax Year", "type": "text", "required": True},
                    {"key": "filing_status", "label": "Filing Status", "type": "select", "required": False, "options": [
                        {"value": "Single", "label": "Single"},
                        {"value": "Married Filing Jointly", "label": "Married Filing Jointly"},
                        {"value": "Married Filing Separately", "label": "Married Filing Separately"},
                        {"value": "Head of Household", "label": "Head of Household"},
                        {"value": "Qualifying Surviving Spouse", "label": "Qualifying Surviving Spouse"},
                    ]},
                ],
                "file_slots": ["tax_document"],
                "recommended": True,
            },
        },
    },
    "insurance": {
        "label": "Insurance",
        "icon": "shield-check",
        "slug": "insurance",
        "subcategories": {
            "auto_insurance": {
                "label": "Auto Insurance",
                "icon": "car",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "start_date", "label": "Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "insurance_card"],
                "recommended": True,
            },
            "health_insurance": {
                "label": "Health Insurance",
                "icon": "heart-pulse",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "member_id", "label": "Member ID", "type": "text", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "group_number", "label": "Group Number", "type": "text", "required": False},
                    {"key": "plan_type", "label": "Plan Type", "type": "select", "required": False, "options": [
                        {"value": "hmo", "label": "HMO - Health Maintenance Organization"},
                        {"value": "ppo", "label": "PPO - Preferred Provider Organization"},
                        {"value": "epo", "label": "EPO - Exclusive Provider Organization"},
                        {"value": "pos", "label": "POS - Point of Service"},
                        {"value": "hdhp", "label": "HDHP - High Deductible Health Plan"},
                        {"value": "catastrophic", "label": "Catastrophic"},
                        {"value": "medicare", "label": "Medicare"},
                        {"value": "medicaid", "label": "Medicaid"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "plan_code", "label": "Plan Code", "type": "text", "required": False},
                    {"key": "effective_date", "label": "Effective Date", "type": "date", "required": False},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "rxbin", "label": "RxBIN", "type": "text", "required": False},
                    {"key": "rxpcn", "label": "RxPCN", "type": "text", "required": False},
                    {"key": "rxgrp", "label": "RxGRP", "type": "text", "required": False},
                ],
                "file_slots": ["card_front", "card_back", "policy_document"],
                "recommended": True,
            },
            "homeowners_insurance": {
                "label": "Homeowners Insurance",
                "icon": "home",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "policy_type", "label": "Policy Type", "type": "select", "required": False, "options": [
                        {"value": "ho1", "label": "HO-1 — Basic Form"},
                        {"value": "ho2", "label": "HO-2 — Broad Form"},
                        {"value": "ho3", "label": "HO-3 — Special Form (Most Common)"},
                        {"value": "ho4", "label": "HO-4 — Renters"},
                        {"value": "ho5", "label": "HO-5 — Comprehensive Form"},
                        {"value": "ho6", "label": "HO-6 — Condo"},
                        {"value": "ho7", "label": "HO-7 — Mobile Home"},
                        {"value": "ho8", "label": "HO-8 — Older Home"},
                    ]},
                    {"key": "premium", "label": "Annual Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                        {"value": "escrowed", "label": "Escrowed with Mortgage"},
                    ]},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                    {"key": "property_address", "label": "Property Address", "type": "textarea", "required": False},
                    {"key": "property_type", "label": "Property Type", "type": "select", "required": False, "options": [
                        {"value": "single_family", "label": "Single-Family Home"},
                        {"value": "condo", "label": "Condo / Co-op"},
                        {"value": "townhouse", "label": "Townhouse"},
                        {"value": "multi_family", "label": "Multi-Family (2-4 Units)"},
                        {"value": "mobile_home", "label": "Mobile / Manufactured Home"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "year_built", "label": "Year Built", "type": "text", "required": False},
                    {"key": "square_footage", "label": "Square Footage", "type": "number", "required": False},
                    {"key": "construction_type", "label": "Construction Type", "type": "select", "required": False, "options": [
                        {"value": "frame", "label": "Frame (Wood)"},
                        {"value": "masonry", "label": "Masonry (Brick/Stone)"},
                        {"value": "masonry_veneer", "label": "Masonry Veneer"},
                        {"value": "fire_resistive", "label": "Fire Resistive"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "roof_type", "label": "Roof Type", "type": "select", "required": False, "options": [
                        {"value": "asphalt_shingle", "label": "Asphalt Shingle"},
                        {"value": "metal", "label": "Metal"},
                        {"value": "tile", "label": "Tile (Clay/Concrete)"},
                        {"value": "slate", "label": "Slate"},
                        {"value": "flat", "label": "Flat / Built-Up"},
                        {"value": "wood_shake", "label": "Wood Shake"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "roof_age", "label": "Roof Age (Years)", "type": "text", "required": False},
                    {"key": "valuation_type", "label": "Valuation Type", "type": "select", "required": False, "options": [
                        {"value": "replacement_cost", "label": "Replacement Cost"},
                        {"value": "actual_cash_value", "label": "Actual Cash Value"},
                        {"value": "extended_replacement", "label": "Extended Replacement Cost"},
                        {"value": "guaranteed_replacement", "label": "Guaranteed Replacement Cost"},
                    ]},
                ],
                "file_slots": ["policy_document", "declarations_page", "home_inventory", "property_photos"],
                "recommended": True,
            },
            "renters_insurance": {
                "label": "Renters Insurance",
                "icon": "building",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                    ]},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                    {"key": "rental_address", "label": "Rental Address", "type": "textarea", "required": False},
                    {"key": "rental_type", "label": "Rental Type", "type": "select", "required": False, "options": [
                        {"value": "apartment", "label": "Apartment"},
                        {"value": "house", "label": "House"},
                        {"value": "condo", "label": "Condo"},
                        {"value": "townhouse", "label": "Townhouse"},
                        {"value": "room", "label": "Room / Shared Housing"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "deductible", "label": "Deductible", "type": "number", "required": False},
                    {"key": "personal_property_limit", "label": "Personal Property Limit", "type": "number", "required": False},
                    {"key": "liability_limit", "label": "Liability Limit", "type": "number", "required": False},
                    {"key": "valuation_type", "label": "Valuation Type", "type": "select", "required": False, "options": [
                        {"value": "replacement_cost", "label": "Replacement Cost"},
                        {"value": "actual_cash_value", "label": "Actual Cash Value"},
                    ]},
                ],
                "file_slots": ["policy_document", "declarations_page", "home_inventory"],
                "recommended": True,
            },
            "life_insurance": {
                "label": "Life Insurance",
                "icon": "heart",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "policy_type", "label": "Policy Type", "type": "select", "required": False, "options": [
                        {"value": "term", "label": "Term Life"},
                        {"value": "whole", "label": "Whole Life"},
                        {"value": "universal", "label": "Universal Life"},
                        {"value": "variable", "label": "Variable Life"},
                        {"value": "variable_universal", "label": "Variable Universal Life"},
                        {"value": "indexed_universal", "label": "Indexed Universal Life (IUL)"},
                        {"value": "guaranteed_universal", "label": "Guaranteed Universal Life (GUL)"},
                        {"value": "final_expense", "label": "Final Expense / Burial"},
                        {"value": "group", "label": "Group Life (Employer)"},
                        {"value": "survivorship", "label": "Survivorship / Second-to-Die"},
                        {"value": "other", "label": "Other"},
                    ]},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                        {"value": "single_premium", "label": "Single Premium"},
                    ]},
                    {"key": "underwriting_class", "label": "Underwriting Class", "type": "select", "required": False, "options": [
                        {"value": "preferred_plus", "label": "Preferred Plus"},
                        {"value": "preferred", "label": "Preferred"},
                        {"value": "standard_plus", "label": "Standard Plus"},
                        {"value": "standard", "label": "Standard"},
                        {"value": "substandard", "label": "Substandard / Table-Rated"},
                        {"value": "guaranteed_issue", "label": "Guaranteed Issue"},
                    ]},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Term End Date", "type": "date", "required": False},
                    {"key": "primary_beneficiary", "label": "Primary Beneficiary", "type": "person", "required": False},
                    {"key": "contingent_beneficiary", "label": "Contingent Beneficiary", "type": "person", "required": False},
                    {"key": "insured_name", "label": "Insured Person", "type": "person", "required": False},
                    {"key": "riders", "label": "Riders / Add-Ons", "type": "textarea", "required": False},
                ],
                "file_slots": ["policy_document", "declarations_page", "beneficiary_designation"],
                "recommended": True,
            },
            "other_insurance": {
                "label": "Other Insurance",
                "icon": "shield-plus",
                "fields": [
                    {"key": "insurance_type", "label": "Insurance Type", "type": "text", "required": True},
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "start_date", "label": "Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "End Date", "type": "date", "required": False},
                ],
                "file_slots": ["policy_document"],
                "recommended": False,
            },
        },
    },
    "business": {
        "label": "Business",
        "icon": "briefcase",
        "slug": "business",
        "subcategories": {
            "llc": {
                "label": "LLCs",
                "icon": "building",
                "field_groups": [
                    {
                        "label": "Business Information",
                        "fields": [
                            {"key": "business_name", "label": "Business Name", "type": "text", "required": True},
                            {"key": "ein", "label": "EIN", "type": "text", "required": False, "encrypted": True},
                            {"key": "formation_date", "label": "Formation Date", "type": "date", "required": False},
                            {"key": "state_of_formation", "label": "State of Formation", "type": "select", "required": False, "options": US_STATES},
                            {"key": "registered_agent", "label": "Registered Agent", "type": "text", "required": False},
                            {"key": "has_employees", "label": "Has Employees", "type": "select", "required": False, "options": [
                                {"value": "yes", "label": "Yes"},
                                {"value": "no", "label": "No"},
                            ]},
                            {"key": "tax_election", "label": "Tax Election", "type": "select", "required": False, "options": [
                                {"value": "single_member", "label": "Single-Member LLC (Disregarded Entity)"},
                                {"value": "partnership", "label": "Multi-Member LLC (Partnership)"},
                                {"value": "s_corp", "label": "S-Corp"},
                                {"value": "c_corp", "label": "C-Corp"},
                            ]},
                        ]
                    },
                    {
                        "label": "Business Address",
                        "fields": [
                            {"key": "address_line_1", "label": "Address Line 1", "type": "text", "required": False},
                            {"key": "address_line_2", "label": "Address Line 2", "type": "text", "required": False},
                            {"key": "apt_suite_unit", "label": "Apt/Suite/Unit", "type": "text", "required": False},
                            {"key": "city", "label": "City", "type": "text", "required": False},
                            {"key": "state", "label": "State", "type": "select", "required": False, "options": US_STATES},
                            {"key": "zip_code", "label": "ZIP Code", "type": "text", "required": False},
                        ]
                    },
                ],
                "file_slots": ["operating_agreement", "formation_documents"],
                "recommended": True,
            },
            "corporation": {
                "label": "Corporations",
                "icon": "building-2",
                "field_groups": [
                    {
                        "label": "Business Information",
                        "fields": [
                            {"key": "business_name", "label": "Business Name", "type": "text", "required": True},
                            {"key": "ein", "label": "EIN", "type": "text", "required": False, "encrypted": True},
                            {"key": "formation_date", "label": "Formation Date", "type": "date", "required": False},
                            {"key": "state_of_incorporation", "label": "State of Incorporation", "type": "select", "required": False, "options": US_STATES},
                            {"key": "registered_agent", "label": "Registered Agent", "type": "text", "required": False},
                            {"key": "has_employees", "label": "Has Employees", "type": "select", "required": False, "options": [
                                {"value": "yes", "label": "Yes"},
                                {"value": "no", "label": "No"},
                            ]},
                            {"key": "tax_election", "label": "Tax Election", "type": "select", "required": False, "options": [
                                {"value": "c_corp", "label": "C-Corp"},
                                {"value": "s_corp", "label": "S-Corp"},
                            ]},
                        ]
                    },
                    {
                        "label": "Business Address",
                        "fields": [
                            {"key": "address_line_1", "label": "Address Line 1", "type": "text", "required": False},
                            {"key": "address_line_2", "label": "Address Line 2", "type": "text", "required": False},
                            {"key": "apt_suite_unit", "label": "Apt/Suite/Unit", "type": "text", "required": False},
                            {"key": "city", "label": "City", "type": "text", "required": False},
                            {"key": "state", "label": "State", "type": "select", "required": False, "options": US_STATES},
                            {"key": "zip_code", "label": "ZIP Code", "type": "text", "required": False},
                        ]
                    },
                ],
                "file_slots": ["articles_of_incorporation", "bylaws", "formation_documents"],
                "recommended": False,
            },
            "partnership": {
                "label": "Partnerships/LLPs",
                "icon": "users",
                "fields": [
                    {"key": "business_name", "label": "Business Name", "type": "text", "required": True},
                    {"key": "ein", "label": "EIN", "type": "text", "required": False, "encrypted": True},
                    {"key": "partner_names", "label": "Partner Names", "type": "textarea", "required": False},
                    {"key": "formation_date", "label": "Formation Date", "type": "date", "required": False},
                ],
                "file_slots": ["partnership_agreement", "formation_documents"],
                "recommended": False,
            },
            "sole_proprietorship": {
                "label": "Sole Proprietorships",
                "icon": "user",
                "fields": [
                    {"key": "business_name", "label": "Business Name", "type": "text", "required": True},
                    {"key": "ein", "label": "EIN", "type": "text", "required": False, "encrypted": True},
                    {"key": "owner_name", "label": "Owner Name", "type": "text", "required": True},
                    {"key": "start_date", "label": "Start Date", "type": "date", "required": False},
                ],
                "file_slots": ["business_documents"],
                "recommended": False,
            },
            "business_license": {
                "label": "Business Licenses & Permits",
                "icon": "file-badge",
                "fields": [
                    {"key": "license_type", "label": "License Type", "type": "text", "required": True},
                    {"key": "license_number", "label": "License Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "issuing_authority", "label": "Issuing Authority", "type": "text", "required": False},
                    {"key": "issue_date", "label": "Issue Date", "type": "date", "required": False},
                    {"key": "expiration_date", "label": "Expiration Date", "type": "date", "required": True},
                ],
                "file_slots": ["license_document"],
                "recommended": True,
            },
            "general_liability": {
                "label": "General Liability (GL)",
                "icon": "shield",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                    ]},
                    {"key": "per_occurrence_limit", "label": "Per Occurrence Limit", "type": "number", "required": False},
                    {"key": "aggregate_limit", "label": "General Aggregate Limit", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance"],
                "recommended": True,
            },
            "professional_liability": {
                "label": "Professional Liability (E&O)",
                "icon": "briefcase",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                    ]},
                    {"key": "coverage_basis", "label": "Coverage Basis", "type": "select", "required": False, "options": [
                        {"value": "claims_made", "label": "Claims-Made"},
                        {"value": "occurrence", "label": "Occurrence"},
                    ]},
                    {"key": "retroactive_date", "label": "Retroactive Date", "type": "date", "required": False},
                    {"key": "per_claim_limit", "label": "Per Claim Limit", "type": "number", "required": False},
                    {"key": "aggregate_limit", "label": "Aggregate Limit", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance"],
                "recommended": True,
            },
            "workers_compensation": {
                "label": "Workers' Compensation",
                "icon": "hard-hat",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "state", "label": "State", "type": "select", "required": False, "options": US_STATES},
                    {"key": "classification_code", "label": "Classification Code", "type": "text", "required": False},
                    {"key": "experience_mod_rate", "label": "Experience Mod Rate (EMR)", "type": "text", "required": False},
                    {"key": "number_of_employees", "label": "Number of Employees", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance"],
                "recommended": True,
            },
            "commercial_property": {
                "label": "Commercial Property",
                "icon": "building",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                    ]},
                    {"key": "property_address", "label": "Property Address", "type": "textarea", "required": False},
                    {"key": "building_value", "label": "Building Value", "type": "number", "required": False},
                    {"key": "contents_value", "label": "Contents Value", "type": "number", "required": False},
                    {"key": "valuation_type", "label": "Valuation Type", "type": "select", "required": False, "options": [
                        {"value": "replacement_cost", "label": "Replacement Cost"},
                        {"value": "actual_cash_value", "label": "Actual Cash Value"},
                        {"value": "functional_replacement", "label": "Functional Replacement Cost"},
                    ]},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance", "property_photos"],
                "recommended": True,
            },
            "commercial_auto": {
                "label": "Commercial Auto",
                "icon": "truck",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "number_of_vehicles", "label": "Number of Vehicles", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance", "vehicle_schedule"],
                "recommended": False,
            },
            "bop": {
                "label": "Business Owner's Policy (BOP)",
                "icon": "shield-check",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "payment_frequency", "label": "Payment Frequency", "type": "select", "required": False, "options": [
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "quarterly", "label": "Quarterly"},
                        {"value": "semi_annual", "label": "Semi-Annual"},
                        {"value": "annual", "label": "Annual"},
                    ]},
                    {"key": "property_address", "label": "Property Address", "type": "textarea", "required": False},
                    {"key": "property_limit", "label": "Property Limit", "type": "number", "required": False},
                    {"key": "liability_limit", "label": "Liability Limit", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance"],
                "recommended": False,
            },
            "cyber_liability": {
                "label": "Cyber Liability",
                "icon": "wifi",
                "fields": [
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": True, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "coverage_basis", "label": "Coverage Basis", "type": "select", "required": False, "options": [
                        {"value": "claims_made", "label": "Claims-Made"},
                        {"value": "occurrence", "label": "Occurrence"},
                    ]},
                    {"key": "retroactive_date", "label": "Retroactive Date", "type": "date", "required": False},
                    {"key": "per_incident_limit", "label": "Per Incident Limit", "type": "number", "required": False},
                    {"key": "aggregate_limit", "label": "Aggregate Limit", "type": "number", "required": False},
                    {"key": "start_date", "label": "Policy Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "Renewal Date", "type": "date", "required": True},
                ],
                "file_slots": ["policy_document", "certificate_of_insurance"],
                "recommended": False,
            },
            "other_business_insurance": {
                "label": "Other Business Insurance",
                "icon": "shield-plus",
                "fields": [
                    {"key": "insurance_type", "label": "Insurance Type", "type": "text", "required": True},
                    {"key": "provider", "label": "Provider", "type": "provider", "required": True},
                    {"key": "policy_number", "label": "Policy Number", "type": "text", "required": False, "encrypted": True},
                    {"key": "premium", "label": "Premium", "type": "number", "required": False},
                    {"key": "start_date", "label": "Start Date", "type": "date", "required": False},
                    {"key": "end_date", "label": "End Date", "type": "date", "required": False},
                ],
                "file_slots": ["policy_document"],
                "recommended": False,
            },
            "tax_document": {
                "label": "Tax Documents",
                "icon": "file-spreadsheet",
                "fields": [
                    {"key": "document_type", "label": "Document Type", "type": "text", "required": True},
                    {"key": "tax_year", "label": "Tax Year", "type": "text", "required": True},
                    {"key": "business_name", "label": "Business Name", "type": "text", "required": False},
                ],
                "file_slots": ["tax_document"],
                "recommended": True,
            },
        },
    },
}

# Date field keys that trigger reminders when approaching expiration
REMINDER_FIELD_KEYS = {"expiration_date", "end_date"}

# Coverage definitions for insurance subcategories
# Each entry defines the layout type, default rows/limits, and whether providers are supported
COVERAGE_DEFINITIONS = {
    "health_insurance": {
        "layout": "health",
        "supports_providers": True,
        "plan_limits": [
            {"key": "deductible_individual_in", "label": "Individual Deductible", "group": "in_network", "sort_order": 0},
            {"key": "deductible_family_in", "label": "Family Deductible", "group": "in_network", "sort_order": 1},
            {"key": "oop_max_individual_in", "label": "Individual OOP Max", "group": "in_network", "sort_order": 2},
            {"key": "oop_max_family_in", "label": "Family OOP Max", "group": "in_network", "sort_order": 3},
            {"key": "deductible_individual_out", "label": "Individual Deductible", "group": "out_of_network", "sort_order": 4},
            {"key": "deductible_family_out", "label": "Family Deductible", "group": "out_of_network", "sort_order": 5},
            {"key": "oop_max_individual_out", "label": "Individual OOP Max", "group": "out_of_network", "sort_order": 6},
            {"key": "oop_max_family_out", "label": "Family OOP Max", "group": "out_of_network", "sort_order": 7},
        ],
        "default_rows": [
            # Outpatient Care
            {"key": "pcp_visit", "label": "Primary Care Visit", "section": "Outpatient Care", "sort_order": 0},
            {"key": "specialist", "label": "Specialist Visit", "section": "Outpatient Care", "sort_order": 1},
            {"key": "urgent_care", "label": "Urgent Care", "section": "Outpatient Care", "sort_order": 2},
            {"key": "emergency_room", "label": "Emergency Room", "section": "Outpatient Care", "sort_order": 3},
            {"key": "preventive_care", "label": "Preventive Care", "section": "Outpatient Care", "sort_order": 4},
            {"key": "mental_health", "label": "Mental Health", "section": "Outpatient Care", "sort_order": 5},
            {"key": "physical_therapy", "label": "Physical Therapy", "section": "Outpatient Care", "sort_order": 6},
            # Diagnostic Services
            {"key": "lab_work", "label": "Lab Work", "section": "Diagnostic Services", "sort_order": 7},
            {"key": "imaging", "label": "Imaging (X-Ray, MRI)", "section": "Diagnostic Services", "sort_order": 8},
            # Inpatient Care
            {"key": "hospitalization", "label": "Hospitalization", "section": "Inpatient Care", "sort_order": 9},
            {"key": "maternity", "label": "Maternity", "section": "Inpatient Care", "sort_order": 10},
            {"key": "outpatient_surgery", "label": "Outpatient Surgery", "section": "Inpatient Care", "sort_order": 11},
            # Prescription Drugs
            {"key": "rx_generic", "label": "Rx — Generic", "section": "Prescription Drugs", "sort_order": 12},
            {"key": "rx_preferred_brand", "label": "Rx — Preferred Brand", "section": "Prescription Drugs", "sort_order": 13},
            {"key": "rx_non_preferred", "label": "Rx — Non-Preferred Brand", "section": "Prescription Drugs", "sort_order": 14},
            {"key": "rx_specialty", "label": "Rx — Specialty", "section": "Prescription Drugs", "sort_order": 15},
            # Other Services
            {"key": "dental", "label": "Dental", "section": "Other Services", "sort_order": 16},
            {"key": "vision", "label": "Vision", "section": "Other Services", "sort_order": 17},
        ],
    },
    "auto_insurance": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Liability Coverage (legally required in most states)
            {"key": "bodily_injury", "label": "Bodily Injury Liability", "section": "Liability Coverage", "sort_order": 0},
            {"key": "property_damage", "label": "Property Damage Liability", "section": "Liability Coverage", "sort_order": 1},
            # Uninsured/Underinsured Motorist Coverage
            {"key": "um_uim_bi", "label": "UM/UIM Bodily Injury", "section": "Uninsured/Underinsured Motorist", "sort_order": 2},
            {"key": "um_uim_pd", "label": "UM/UIM Property Damage", "section": "Uninsured/Underinsured Motorist", "sort_order": 3},
            # Physical Damage Coverage (protects your vehicle)
            {"key": "collision", "label": "Collision", "section": "Physical Damage Coverage", "sort_order": 4},
            {"key": "comprehensive", "label": "Comprehensive", "section": "Physical Damage Coverage", "sort_order": 5},
            # Additional Coverage
            {"key": "medical_payments", "label": "Medical Payments / PIP", "section": "Additional Coverage", "sort_order": 6},
            {"key": "rental_reimbursement", "label": "Rental Reimbursement", "section": "Additional Coverage", "sort_order": 7},
            {"key": "roadside_assistance", "label": "Roadside Assistance", "section": "Additional Coverage", "sort_order": 8},
        ],
    },
    "homeowners_insurance": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Property Coverage
            {"key": "dwelling_a", "label": "Dwelling (Coverage A)", "section": "Property Coverage", "sort_order": 0},
            {"key": "other_structures_b", "label": "Other Structures (Coverage B)", "section": "Property Coverage", "sort_order": 1},
            {"key": "personal_property_c", "label": "Personal Property (Coverage C)", "section": "Property Coverage", "sort_order": 2},
            {"key": "loss_of_use_d", "label": "Loss of Use (Coverage D)", "section": "Property Coverage", "sort_order": 3},
            # Liability Coverage
            {"key": "personal_liability_e", "label": "Personal Liability (Coverage E)", "section": "Liability Coverage", "sort_order": 4},
            {"key": "medical_payments_f", "label": "Medical Payments (Coverage F)", "section": "Liability Coverage", "sort_order": 5},
            # Personal Property Sub-Limits
            {"key": "jewelry_sublimit", "label": "Jewelry / Watches Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 6},
            {"key": "electronics_sublimit", "label": "Electronics Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 7},
            {"key": "firearms_sublimit", "label": "Firearms Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 8},
            {"key": "cash_sublimit", "label": "Cash / Securities Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 9},
            # Optional Coverage
            {"key": "water_backup", "label": "Water Backup / Sump Overflow", "section": "Optional Coverage", "sort_order": 10},
            {"key": "service_line", "label": "Service Line Coverage", "section": "Optional Coverage", "sort_order": 11},
            {"key": "identity_theft", "label": "Identity Theft Protection", "section": "Optional Coverage", "sort_order": 12},
            {"key": "equipment_breakdown", "label": "Equipment Breakdown", "section": "Optional Coverage", "sort_order": 13},
        ],
    },
    "renters_insurance": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Core Coverage
            {"key": "personal_property_c", "label": "Personal Property (Coverage C)", "section": "Core Coverage", "sort_order": 0},
            {"key": "loss_of_use_d", "label": "Loss of Use (Coverage D)", "section": "Core Coverage", "sort_order": 1},
            {"key": "personal_liability_e", "label": "Personal Liability (Coverage E)", "section": "Core Coverage", "sort_order": 2},
            {"key": "medical_payments_f", "label": "Medical Payments to Others (Coverage F)", "section": "Core Coverage", "sort_order": 3},
            # Personal Property Sub-Limits
            {"key": "jewelry_sublimit", "label": "Jewelry / Watches Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 4},
            {"key": "electronics_sublimit", "label": "Electronics Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 5},
            {"key": "cash_sublimit", "label": "Cash / Securities Sub-Limit", "section": "Personal Property Sub-Limits", "sort_order": 6},
            # Optional Coverage
            {"key": "identity_theft", "label": "Identity Theft Protection", "section": "Optional Coverage", "sort_order": 7},
            {"key": "water_backup", "label": "Water Backup / Sump Overflow", "section": "Optional Coverage", "sort_order": 8},
        ],
    },
    "life_insurance": {
        "layout": "life",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Policy Details
            {"key": "death_benefit", "label": "Death Benefit", "section": "Policy Details", "sort_order": 0},
            {"key": "policy_type", "label": "Policy Type", "section": "Policy Details", "sort_order": 1},
            {"key": "cash_value", "label": "Cash Value", "section": "Policy Details", "sort_order": 2},
            # Beneficiaries
            {"key": "primary_beneficiary", "label": "Primary Beneficiary", "section": "Beneficiaries", "sort_order": 3},
            {"key": "contingent_beneficiary", "label": "Contingent Beneficiary", "section": "Beneficiaries", "sort_order": 4},
            # Riders & Additional Benefits
            {"key": "riders", "label": "Riders / Add-Ons", "section": "Riders & Additional Benefits", "sort_order": 5},
            {"key": "waiver_of_premium", "label": "Waiver of Premium Rider", "section": "Riders & Additional Benefits", "sort_order": 6},
            {"key": "accidental_death", "label": "Accidental Death Benefit", "section": "Riders & Additional Benefits", "sort_order": 7},
            {"key": "accelerated_death", "label": "Accelerated Death Benefit", "section": "Riders & Additional Benefits", "sort_order": 8},
            {"key": "child_rider", "label": "Child Term Rider", "section": "Riders & Additional Benefits", "sort_order": 9},
            {"key": "long_term_care", "label": "Long-Term Care Rider", "section": "Riders & Additional Benefits", "sort_order": 10},
        ],
    },
    "other_insurance": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [],
    },
    "general_liability": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Bodily Injury & Property Damage
            {"key": "bodily_injury", "label": "Bodily Injury", "section": "Bodily Injury & Property Damage", "sort_order": 0},
            {"key": "property_damage", "label": "Property Damage", "section": "Bodily Injury & Property Damage", "sort_order": 1},
            # Additional Coverage
            {"key": "personal_advertising_injury", "label": "Personal & Advertising Injury", "section": "Additional Coverage", "sort_order": 2},
            {"key": "products_completed_ops", "label": "Products-Completed Operations", "section": "Additional Coverage", "sort_order": 3},
            {"key": "fire_damage_legal", "label": "Fire Damage (Any One Fire)", "section": "Additional Coverage", "sort_order": 4},
            {"key": "medical_expense", "label": "Medical Expense (Any One Person)", "section": "Additional Coverage", "sort_order": 5},
        ],
    },
    "professional_liability": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Coverage Limits
            {"key": "per_claim", "label": "Per Claim Limit", "section": "Coverage Limits", "sort_order": 0},
            {"key": "aggregate", "label": "Aggregate Limit", "section": "Coverage Limits", "sort_order": 1},
            {"key": "defense_costs", "label": "Defense Costs", "section": "Coverage Limits", "sort_order": 2},
            # Additional Coverage
            {"key": "disciplinary_proceedings", "label": "Disciplinary Proceedings", "section": "Additional Coverage", "sort_order": 3},
            {"key": "cyber_incident", "label": "Cyber Incident Sub-Limit", "section": "Additional Coverage", "sort_order": 4},
        ],
    },
    "workers_compensation": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Part A — Statutory
            {"key": "statutory_benefits", "label": "Statutory Benefits", "section": "Part A — Workers' Compensation", "sort_order": 0},
            # Part B — Employers' Liability
            {"key": "each_accident", "label": "Each Accident", "section": "Part B — Employers' Liability", "sort_order": 1},
            {"key": "disease_each_employee", "label": "Disease — Each Employee", "section": "Part B — Employers' Liability", "sort_order": 2},
            {"key": "disease_policy_limit", "label": "Disease — Policy Limit", "section": "Part B — Employers' Liability", "sort_order": 3},
        ],
    },
    "commercial_property": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Property Coverage
            {"key": "building", "label": "Building", "section": "Property Coverage", "sort_order": 0},
            {"key": "business_personal_property", "label": "Business Personal Property", "section": "Property Coverage", "sort_order": 1},
            {"key": "tenants_improvements", "label": "Tenants' Improvements", "section": "Property Coverage", "sort_order": 2},
            # Business Income
            {"key": "business_income", "label": "Business Income", "section": "Business Income", "sort_order": 3},
            {"key": "extra_expense", "label": "Extra Expense", "section": "Business Income", "sort_order": 4},
            # Additional Coverage
            {"key": "equipment_breakdown", "label": "Equipment Breakdown", "section": "Additional Coverage", "sort_order": 5},
            {"key": "spoilage", "label": "Spoilage", "section": "Additional Coverage", "sort_order": 6},
            {"key": "ordinance_law", "label": "Ordinance or Law", "section": "Additional Coverage", "sort_order": 7},
        ],
    },
    "commercial_auto": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Liability Coverage
            {"key": "bodily_injury", "label": "Bodily Injury Liability", "section": "Liability Coverage", "sort_order": 0},
            {"key": "property_damage", "label": "Property Damage Liability", "section": "Liability Coverage", "sort_order": 1},
            # Uninsured/Underinsured
            {"key": "um_uim_bi", "label": "UM/UIM Bodily Injury", "section": "Uninsured/Underinsured Motorist", "sort_order": 2},
            {"key": "um_uim_pd", "label": "UM/UIM Property Damage", "section": "Uninsured/Underinsured Motorist", "sort_order": 3},
            # Physical Damage
            {"key": "collision", "label": "Collision", "section": "Physical Damage", "sort_order": 4},
            {"key": "comprehensive", "label": "Comprehensive", "section": "Physical Damage", "sort_order": 5},
            # Additional
            {"key": "hired_auto", "label": "Hired Auto Liability", "section": "Additional Coverage", "sort_order": 6},
            {"key": "non_owned_auto", "label": "Non-Owned Auto Liability", "section": "Additional Coverage", "sort_order": 7},
            {"key": "cargo", "label": "Cargo / Motor Truck Cargo", "section": "Additional Coverage", "sort_order": 8},
        ],
    },
    "bop": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # Property Coverage
            {"key": "building", "label": "Building", "section": "Property Coverage", "sort_order": 0},
            {"key": "business_personal_property", "label": "Business Personal Property", "section": "Property Coverage", "sort_order": 1},
            {"key": "business_income", "label": "Business Income", "section": "Property Coverage", "sort_order": 2},
            # General Liability
            {"key": "general_liability_per_occurrence", "label": "Per Occurrence", "section": "General Liability", "sort_order": 3},
            {"key": "general_liability_aggregate", "label": "General Aggregate", "section": "General Liability", "sort_order": 4},
            {"key": "products_completed_ops", "label": "Products-Completed Operations", "section": "General Liability", "sort_order": 5},
            # Additional Coverage
            {"key": "equipment_breakdown", "label": "Equipment Breakdown", "section": "Additional Coverage", "sort_order": 6},
            {"key": "data_breach", "label": "Data Breach", "section": "Additional Coverage", "sort_order": 7},
        ],
    },
    "cyber_liability": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [
            # First-Party Coverage
            {"key": "data_breach_response", "label": "Data Breach Response", "section": "First-Party Coverage", "sort_order": 0},
            {"key": "network_business_interruption", "label": "Network Business Interruption", "section": "First-Party Coverage", "sort_order": 1},
            {"key": "cyber_extortion", "label": "Cyber Extortion / Ransomware", "section": "First-Party Coverage", "sort_order": 2},
            {"key": "data_recovery", "label": "Data Recovery", "section": "First-Party Coverage", "sort_order": 3},
            # Third-Party Coverage
            {"key": "network_security_liability", "label": "Network Security Liability", "section": "Third-Party Coverage", "sort_order": 4},
            {"key": "privacy_liability", "label": "Privacy Liability", "section": "Third-Party Coverage", "sort_order": 5},
            {"key": "regulatory_defense", "label": "Regulatory Defense & Penalties", "section": "Third-Party Coverage", "sort_order": 6},
            {"key": "media_liability", "label": "Media Liability", "section": "Third-Party Coverage", "sort_order": 7},
        ],
    },
    "other_business_insurance": {
        "layout": "standard",
        "supports_providers": False,
        "plan_limits": [],
        "default_rows": [],
    },
}
